[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm Interpreter"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "interpreter"]
license = "MIT"
name = "revm-interpreter"
repository = "https://github.com/bluealloy/revm"
version = "1.3.0"
readme = "../../README.md"

[dependencies]
revm-primitives = { path = "../primitives", version = "1.3.0", default-features = false }

# optional
serde = { version = "1.0", features = ["derive", "rc"], optional = true }

[features]
default = ["std"]
std = ["revm-primitives/std"]
serde = ["dep:serde", "revm-primitives/serde"]
arbitrary = ["std", "revm-primitives/arbitrary"]

optimism = ["revm-primitives/optimism"]
taiko = ["revm-primitives/taiko"]

dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
]
memory_limit = ["revm-primitives/memory_limit"]
no_gas_measuring = ["revm-primitives/no_gas_measuring"]
optional_balance_check = ["revm-primitives/optional_balance_check"]
optional_block_gas_limit = ["revm-primitives/optional_block_gas_limit"]
optional_eip3607 = ["revm-primitives/optional_eip3607"]
optional_gas_refund = ["revm-primitives/optional_gas_refund"]
optional_no_base_fee = ["revm-primitives/optional_no_base_fee"]
